"""empty message

Revision ID: b6d52a619ba3
Revises: 
Create Date: 2023-07-24 14:55:39.548534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d52a619ba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('theatre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'theatre', ['theatre_id'], ['id'])
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('theatre_id')
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
